/**
 * Centralized API Service for Company AI Assistant
 */

export const API_BASE = (typeof window !== "undefined" && window.location.origin.includes('3000'))
  ? "http://127.0.0.1:8000/api"
  : "/api";

if (typeof window !== "undefined") {
  window.__API_BASE__ = API_BASE;
}

/**
 * Helper to get Bearer authentication headers
 */
const getHeaders = () => {
  const token = localStorage.getItem("api_token") || "";
  return {
    "Content-Type": "application/json",
    "Authorization": token ? `Bearer ${token}` : ""
  };
};

/**
 * Authenticate User (login)
 */
export async function login(username, password) {
  const response = await fetch(`${API_BASE}/auth.php`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ action: "login", username, password })
  });

  const data = await response.json();
  if (data.success) {
    localStorage.setItem("api_token", data.token);
    localStorage.setItem("user", JSON.stringify(data.user));
  }
  return data;
}

/**
 * Logout User
 */
export async function logout() {
  try {
    await fetch(`${API_BASE}/auth.php`, {
      method: "POST",
      headers: getHeaders(),
      body: JSON.stringify({ action: "logout" })
    });
  } catch (e) {
    console.warn("Logout error:", e);
  } finally {
    localStorage.removeItem("api_token");
    localStorage.removeItem("user");
  }
}

/**
 * Get current cached authenticated user
 */
export function getAuthUser() {
  const userStr = localStorage.getItem("user");
  if (!userStr) return null;
  try {
    return JSON.parse(userStr);
  } catch (e) {
    return null;
  }
}

/**
 * Send Chat Question to AI Assistant API
 */
export async function sendMessage(message, sessionUuid = null) {
  const response = await fetch(`${API_BASE}/chat.php`, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify({
      message,
      session_uuid: sessionUuid
    })
  });

  return await response.json();
}

/**
 * Generate Report (PDF, Excel, CSV)
 */
export async function generateReport(type = "attendance", format = "pdf") {
  const response = await fetch(`${API_BASE}/report.php`, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify({ type, format })
  });

  return await response.json();
}

/**
 * Get Download URL for report
 */
export function getDownloadUrl(reportId) {
  const token = localStorage.getItem("api_token") || "";
  return `${API_BASE}/download.php?id=${reportId}&token=${encodeURIComponent(token)}`;
}

/**
 * Trigger File Download via Browser Blob
 */
export async function triggerFileDownload(reportId, fileName = "report.pdf") {
  const token = localStorage.getItem("api_token") || "";
  const response = await fetch(`${API_BASE}/download.php?id=${reportId}`, {
    method: "GET",
    headers: {
      "Authorization": `Bearer ${token}`
    }
  });

  if (!response.ok) {
    throw new Error("Download failed");
  }

  const blob = await response.blob();
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.URL.revokeObjectURL(url);
}

/**
 * Email Report to Department Group (HR, Finance, Management, Admin)
 */
export async function emailReport(reportId, group = "HR") {
  const response = await fetch(`${API_BASE}/email.php`, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify({
      report_id: reportId,
      group: group,
      subject: "Company AI Generated Report",
      message: "Please review the attached official company report generated by Company AI Assistant."
    })
  });

  return await response.json();
}

/**
 * Fetch live database audit log records
 */
export async function getAuditLogs(limit = 50, filter = "") {
  const params = new URLSearchParams({ limit: String(limit) });
  if (filter) params.append("q", filter);
  const response = await fetch(`${API_BASE}/audit_logs.php?${params.toString()}`, {
    method: "GET",
    headers: getHeaders()
  });
  return await response.json();
}

